---
- name: systemd restart {{ blackbox_service_name }}
  systemd:
    name: "{{ blackbox_service_name }}"
    state: restarted
    daemon_reload: yes

- name: initd restart {{ blackbox_service_name }}
  service:
    name: "{{ blackbox_service_name }}"
    state: restarted
